
class Exceptions:
    def __init__(self) -> None:
        pass

    def ValueError(self) -> ValueError:
        print('ValueError: The value is not correct')
        return ValueError